services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python run.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio_4oeu
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5001

  - type: web
    name: portfolio-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://portfolio-backend.onrender.com/api
